.github/dependabot.yml
This way we can just merge PRs instead of needing to update ourselves manually
=> chore: add Dependabot for npm dependencies

framer-route-animation/app/root.tsx
Using the key responds to changes in searchParams, which duplicate the animation for pages the signs searchParams in useEffect when first render
=> fix(framer-route-animation): use `location.pathname` instead of `key`

msw/package.json
**What existing problem does the pull request solves**
- Support initialize msw mocks when working in local development.
Fixes #44 
**Special note to reviewers**
- Dev dependency `binode` is added to initialize msw mocks then start `remix dev`.
- Upgrade dev dependency `msw` to `^0.47.3` in order to work with `binode` (Related PR: https://github.com/remix-run/indie-stack/pull/158).
=> feat(msw): update `dev` script to initialize mocks

vanilla-extract/package.json
I was checking out vanilla extract + remix and noticed that the example did not run unless this dependency was added. Looks like it's used in:
https://github.com/remix-run/examples/blob/main/vanilla-extract/app/entry.server.tsx#L17-L29
=> fix(vanilla-extract): add `isbot` dependency

_official-blog-tutorial/app/models/note.server.ts, _official-blog-tutorial/app/models/post.server.ts, _official-blog-tutorial/app/models/user.server.ts, _official-blog-tutorial/app/root.tsx, _official-blog-tutorial/app/routes/healthcheck.tsx, _official-blog-tutorial/app/routes/join.tsx, _official-blog-tutorial/app/routes/login.tsx, _official-blog-tutorial/app/routes/logout.tsx, _official-blog-tutorial/app/routes/notes.tsx, _official-blog-tutorial/app/routes/notes/$noteId.tsx, _official-blog-tutorial/app/routes/notes/new.tsx, _official-blog-tutorial/app/routes/posts/$slug.tsx, _official-blog-tutorial/app/routes/posts/admin.tsx, _official-blog-tutorial/app/routes/posts/admin/new.tsx, _official-blog-tutorial/app/routes/posts/index.tsx
See https://github.com/remix-run/remix/releases/tag/remix@1.6.5
---
Closes #34
=> fix(_official-blog-tutorial): fix `useActionData`/`useLoaderData` usage

_official-jokes/app/routes/jokes.tsx, _official-jokes/app/routes/jokes/$jokeId.tsx, _official-jokes/app/routes/jokes/index.tsx, _official-jokes/app/routes/jokes/new.tsx, _official-jokes/app/routes/jokes[.]rss.tsx, _official-jokes/app/routes/login.tsx, _official-jokes/app/routes/logout.tsx, _official-jokes/app/utils/request.server.ts
See https://github.com/remix-run/remix/releases/tag/remix@1.6.5
=> fix(_official-jokes): fix `useActionData`/`useLoaderData` usage

framer-route-animation/README.md
Links to the react router documentation in the framer-route-animation readme were not working.
=> docs(framer-motion-animation): fix broken links

client-only-components/app/routes/index.tsx
`<ClientOnly />` calls its child. 
https://github.com/sergiodxa/remix-utils/blob/main/src/react/client-only.tsx#L30
=> fix(client-only-components): fix ClientOnly children call

_official-realtime-app/app/root.tsx, _official-realtime-app/app/routes/dev.null.ts, _official-realtime-app/app/use-revalidator.tsx, _official-realtime-app/package.json, sse-chat/package.json, sse-counter/package.json
This upgrade the Remix Utils dependency in the SSE examples (the chat, counter and realtime app).
In the realtime app it also replace the useRevalidator built on top of Remix Utils's useDataRefresh for the now built-in useRevalidator hook and removes the `/dev/null` action required to make useDataRefresh works.
=> chore(_official-realtime-app,sse-chat,sse-counter): upgrade `remix-utils`

_official-blog-tutorial/package.json
Apparently we need to add the `-p` flag when running `tsc` on the `cypress` folder
- https://github.com/remix-run/indie-stack/actions/runs/3951228293/jobs/6764810424
- https://github.com/remix-run/blues-stack/actions/runs/3951125579/jobs/6764576532
- https://github.com/remix-run/grunge-stack/actions/runs/3951229138/jobs/6764812112
=> fix(_official-blog-tutorial): fix `typecheck` script

firebase/.gitignore, firebase/README.md, firebase/firebase.json, firebase/functions.yaml, firebase/functions/index.js, firebase/package.json
Reopening #5, https://github.com/remix-run/remix/pull/3398 against remix-run/examples
Deploy to firebase functions and hosting
Closes: Discussion at https://github.com/remix-run/remix/pull/1811#issuecomment-1050238130
Testing Strategy:
- Testing locally against emulator with JS enabled and disabled
- Testing locally against production with JS enabled and disabled
- Following deploy instructions and testing remote with JS enabled and disabled
=> feat(firebase): deploy to Cloud Functions for Firebase

firebase/firebase.json, firebase/package.json
- Use node 16 in firebase example
- An exact node version is needed in firebase/package.json as Firebase uses this to determine which version of node to use for the functions when you run `firebase deploy`. Setting this to 14 does not work, as this conflicts with the root .nvmrc (16). Setting to 14 will result in "Unsupported engine" errors from both yarn and npm install. This could be skipped using `yarn  --ignore-engines`, but I don't think that's a great experience for an example project. Previous discussion: https://github.com/remix-run/remix/pull/3398#discussion_r890170777
- Move hosting to port 5002 to avoid macOS port
- https://developer.apple.com/forums/thread/682332
- https://stackoverflow.com/questions/57537355/firebase-serve-error-port-5000-is-not-open-could-not-start-functions- …
=> fix(firebase): fix several things

image-resize/app/components/image.tsx, image-resize/app/routes/assets/resize/$.ts, image-resize/app/routes/index.tsx
Fix the following issues: 
Build failed with 1 error: No matching export in "app/components/image.tsx" for import "Image"
Warning: Unsupported style property margin-left, margin-right, align-items, overflow-x.
Property 'alt' is missing in type
Module '"@remix-run/node"' has no exported member 'Params'.
=> fix(image-resize): fix build error and warnings

_official-blog-tutorial/tailwind.config.ts, _official-realtime-app/tailwind.config.ts, tailwindcss/tailwind.config.ts, yarn.lock
Due to `@remix-run/eslint-config` having an older version of `@typescript-eslint/*` in its `dependencies`, the type import was removed automatically
In order to make sure this is fixed with other people that have an outdated lockfile, I created https://github.com/remix-run/remix/pull/5948
=> chore: fresh install

tailwindcss/README.md
The tailwind configuration file was migrated to `.ts` a few days ago, which wasn't reflected in the README. This PR fixes that.
=> docs(tailwindcss): fix configuration link

emotion/app/root.tsx
This solves the render loop when loading the emotion example. As far as I can see, we only need to re-inject the styles on the client if the top level component gets unmounted (because that removes the document head, where the styles are).
My original PR had removed all of the code related to this re-injection, but we do need it for that case.
Original description below.
~However, when you trigger the catch boundary on the client, you loose all the styles, since the entire document is re-rendered. This same problem exists in the Chakra example, but you can't easily tell, since there is no link you can follow to trigger the error boundary on the client.~
I finally understand what the code I was removed was trying to do (add the styles back in after re-mounting the document), but it was …
=> fix(emotion): fix render loop

yarn.lock
Did this by running `npx yarn-deduplicate && rm -rf ./node_modules && yarn` (just like I did in https://github.com/remix-run/remix/pull/6108)
- https://github.com/scinos/yarn-deduplicate
- https://npm.im/yarn-deduplicate
=> chore: deduplicate `yarn.lock`

.github/workflows/deduplicate-yarn.yml
We use it in the `format` workflow as well
https://github.com/remix-run/examples/blob/cff408e8841e8d6f24c3e4588e7f63985125ee4f/.github/workflows/format.yml#L43-L44
=> chore: use GitHub bot in `deduplicate-yarn` workflow

mantine/app/clientStyleContext.tsx, mantine/app/entry.client.tsx, mantine/app/root.tsx, mantine/app/routes/error.tsx, mantine/app/routes/index.tsx
This fixes a couple of issues with the Mantine example:
- There was a flash of unstyled content on load due to missing `<StylesPlaceholder />`.
- The styles were removed from the document when navigating between error routes and non-error routes. This is due to the way in which Remix re-renders the entire document from the root when rendering a root-level error component. The fix is based on [correiarmjoao/remix-with-mantine](https://github.com/correiarmjoao/remix-with-mantine) by @correiarmjoao (shared in https://github.com/remix-run/remix/issues/1136).
=> fix(mantine): fix FOUC and handle error styles

emotion/app/entry.client.tsx, emotion/package.json
Not much to say, just updates react and react-dom (plus types) and uses the `hydrateRoot` api. Seems to work without any issues.
=> feat(emotion): use React 18

tailwindcss/app/root.tsx, tailwindcss/app/routes/_index.tsx, tailwindcss/app/routes/index.tsx, tailwindcss/package.json, tailwindcss/remix.config.js
Fixes https://github.com/remix-run/remix/issues/7076
The Tailwind example is pinned to Remix v1.14.x which doesn't support the `tailwind: true` flag, so this example is currently broken due to missing styles. I've updated the example to the same versioning scheme but targeting the minimum required range of `1.16.x`.
To minimise deprecation warnings in the terminal, I've opted into the same set of feature flags used in the tutorial examples.
=> fix(tailwind): update to required Remix version
